package model;/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import model.Inventario;
import org.junit.Test;
import org.mockito.Mockito;

import java.util.ArrayList;
import java.util.List;

import static org.mockito.Mockito.verify;

public class MockingTests {
    @Test public void testSomeLibraryMethod() {
        List<String> lista = Mockito.mock(ArrayList.class);

        Inventario inventario = new Inventario(lista);

        inventario.agregar( "item 1");


        verify(lista).add("item 1");

    }
}
