@startuml
skinparam classAttributeIconSize 0

interface Reloj
Reloj : ahora() Date

Reloj <|.. FakeClock
FakeClock : ahora() Date

Reloj <|.. RelojProductivo
RelojProductivo : ahora() Date


Clima *- Reloj

@enduml
